version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    restart: "no"
  mltrainer: &mltrainer
    environment: &mltrainer_env
      DEPLOY_ENV: dev
    volumes: &mltrainer_volumes
      {%-if cookiecutter.use_submodule_for_deploy_code %}
      - ./{{cookiecutter.deploy_project_dir}}/sys/sudoer:/etc/sudoers.d/${APP_TYPE:-mltrainer}
      - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/sys/init.sh
      - ./{{cookiecutter.deploy_project_dir}}/sys/init.sh:/code/init/init.sh
      - ./{{cookiecutter.deploy_project_dir}}:/code/{{cookiecutter.deploy_project_dir}}
      {%-else %}
      - ./sys/sudoer:/etc/sudoers.d/$APP_TYPE
      - ./sys/init.sh:/code/init/init.sh
      # retrocompat
      - ./sys/init.sh:/code/sys/init.sh
      {%- endif%}
{%- if not cookiecutter.no_lib %}
      - ./lib:/code/lib
{%- endif%}
      - ./local:/code/local
      - ./src:/code/src
      - ./tests:/code/tests
      - ./tox.ini:/code/tox.ini
      - ./.tox:/code/.tox
      - ./requirements:/code/requirements
services:
  {{cookiecutter.app_type}}:
    <<: [ *mltrainer ]
    environment:
      <<: [ *mltrainer_env ]
      IMAGE_MODE: train
    ports:
    - "${MLTRAINER__VSCODE_LISTEN:-0.0.0.0}:${MLTRAINER__VSCODE_PORT:-5678}:5678"
