version: '3.7'
x-images:
  env: &env
    env_file: [.env, docker.env]
    environment: &env_vars
      {% if cookiecutter.cache_system == 'redis' %}REDIS_URL: "${REDIS_URL:-redis://redis:6379/1}"{%endif%}
      MLTRAINER__USER_UID: "${MLTRAINER__USER_UID:-1000}"
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    <<: [ *env ]
    depends_on: [{% if cookiecutter.cache_system%}"{{cookiecutter.cache_system}}"{%endif%}]
    tty: true
    # latest image is only used in prod (without dev & test tools)
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}-dev"
    environment: &mltrainer_env
      <<: [ *env_vars ]
      PROJECT_DIR: "${PROJECT_DIR:-/code/src/{{cookiecutter.mltrainer_project_name}}/}"
      PROJECT_PACKAGE: "${PROJECT_PACKAGE:-{{cookiecutter.mltrainer_project_name}}}"
      EXTRA_USER_DIRS: ""
      TRACKING_SERVER_PORT: "${TRACKING_SERVER_PORT:-5000}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-minio}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-minio123}"
      AWS_STORAGE_BUCKET_NAME: "${AWS_STORAGE_BUCKET_NAME:-mlflow}"
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL:-http://host.docker.internal:9000/}"
      MLFLOW_S3_ENDPOINT_URL: "${MLFLOW_S3_ENDPOINT_URL:-http://host.docker.internal:9000/}"
      MODEL_STAGE: "${MODEL_STAGE:-production}"
      MODEL_PATHS: "${MODEL_PATHS:-/code/src/{{cookiecutter.lname}}}"
      MLFLOW_TRACKING_URI: "${MLFLOW_TRACKING_URI:-http://host.docker.internal:5000}"
      MLFLOW_TRACKING_USERNAME: "${MLFLOW_TRACKING_USERNAME:-mlflow}"
      MLFLOW_TRACKING_PASSWORD: "${MLFLOW_TRACKING_PASSWORD:-mlflow}"
      MLFLOW_TRACKING_INSECURE_TLS: "${MLFLOW_TRACKING_INSECURE_TLS:-true}"
      ARTIFACTS_ROOT: "${ARTIFACTS_ROOT:-s3://minio}"
      DATA_PATH: "${DATA_PATH:-/code/data}"
    {% if cookiecutter.with_nvidia%}
    runtime: nvidia
    {%endif%}
    volumes:
    - ./sys/scripts:/code/sys/scripts
    - logs:/logs/
    - ./data:/code/data
    - ./notebooks:/code/notebooks
    - ./models:/code/models
services:
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
{% if cookiecutter.cache_system%}  {{cookiecutter.cache_system}}:
    <<: [ *env ]
    image: "{{cookiecutter.cache_image}}"
    hostname: {{cookiecutter.cache_system}}
    {% if cookiecutter.cache_system in ['redis'] %}
    volumes:
    - 'redis:/data'
    {% endif %}
{%endif %}
volumes:
  logs:
{% if cookiecutter.cache_system in ['redis']%}  {{cookiecutter.cache_system}}:{%endif%}
