version: '3.7'
x-{{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
  volumes:
  - ./local.py:/code/src/{{cookiecutter.mltrainer_settings.replace('.', '/')}}/local.py
  image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}"
services:
  {{cookiecutter.app_type}}:
    restart: unless-stopped
    <<: [ *{{cookiecutter.app_type}} ]
{% if cookiecutter.cache_system%}  {{cookiecutter.cache_system}}:
    restart: unless-stopped
{%endif%}           
