version: '3.7'
x-images:
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build: {context: ".", args: {BUILD_DEV: "y"}}
services:
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
