---
{{cookiecutter.app_type}}_servers: {{cookiecutter.lname}}_servers
cops_{{cookiecutter.app_type}}_name: "{{cookiecutter.lname}}"
cops_mltrainer_project_module_name: "{{cookiecutter.mltrainer_project_name}}"
cops_{{cookiecutter.app_type}}_tld_domain: "{{cookiecutter.tld_domain}}"
cops_{{cookiecutter.app_type}}_docker_image: "{{cookiecutter.docker_image}}"
cops_{{cookiecutter.app_type}}_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_{{cookiecutter.app_type}}_docker_env_extra: ""
cops_{{cookiecutter.app_type}}_dotenv_extra: |-
  MLTRAINER__USER_UID={{'{{'}}cops_mltrainer_user_uid}}
cops_mltrainer_restarted_services: "{{"{{"}}cops_mltrainer_restarted_services_default.replace(' mltrainer', ' mltrainer')}}"
cops_mltrainer_http_protect_user: "root"
cops_mltrainer_http_protect_password: "rootroot"
cops_mltrainer_user_uid: 1000
